# Generated by Django 5.0.6 on 2024-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.IntegerField()),
                ('age', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
