# Generated by Django 5.0.6 on 2024-06-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_user',
            name='number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
