# Generated by Django 5.0.6 on 2024-06-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0002_basic_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_user',
            name='User_Id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='basic_user',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='basic_user',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='basic_user',
            name='number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
