# Generated by Django 5.0.6 on 2024-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0003_alter_basic_user_user_id_alter_basic_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_user',
            name='v_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
