# Generated by Django 5.0.6 on 2024-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_user", "0004_basic_user_v_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="basic_user",
            name="is_user_verifyed",
            field=models.BooleanField(default=False),
        ),
    ]
